[package]
name = "substratekitties"
version = "0.1.0"
authors = ["Shawn Tabrizi"]
edition = "2018"

[features]
default = ['std']
std = [
    'serde',
    'codec/std',
    'support/std',
    'system/std',
    'runtime-io/std',
    'sr-primitives/std',
]

[dependencies.serde]
version = "1.0"
optional = true

[dependencies.codec]
default-features = false
features = ['derive']
package = 'parity-scale-codec'
version = '1.0.0'

[dependencies.support]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-support'
rev = '47b158b7a04bf0f5cd542a468076a7fda29648a4'

[dependencies.system]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'frame-system'
rev = '47b158b7a04bf0f5cd542a468076a7fda29648a4'

[dependencies.sr-primitives]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-primitives'
rev = '47b158b7a04bf0f5cd542a468076a7fda29648a4'

[dependencies.runtime-io]
default_features = false
git = 'https://github.com/paritytech/substrate.git'
package = 'sr-io'
rev = '47b158b7a04bf0f5cd542a468076a7fda29648a4'

[dev-dependencies.primitives]
git = 'https://github.com/paritytech/substrate.git'
package = 'substrate-primitives'
rev = '47b158b7a04bf0f5cd542a468076a7fda29648a4'

[dev-dependencies.balances]
git = 'https://github.com/paritytech/substrate.git'
package = 'pallet-balances'
rev = '47b158b7a04bf0f5cd542a468076a7fda29648a4'
